/* sign.c
 *
 * Copyright (C) 2006-2025 wolfSSL Inc.
 *
 * This file is part of wolfModel.
 *
 * wolfModel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfModel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <time.h>
#include <sys/stat.h>

#ifndef WOLFSSL_USER_SETTINGS
    #include <wolfssl/options.h>
#endif
#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/ecc.h>
#include <wolfssl/wolfcrypt/sha256.h>
#include <wolfssl/wolfcrypt/random.h>
#include <wolfssl/wolfcrypt/error-crypt.h>

/* Pull in wolfModel constants to ensure consistency */
#include <wolfmodel/wolfmodel.h>

#define ECC256_KEY_SIZE  32
#define MAX_IMAGE_SIZE   (64 * 1024 * 1024) /* 64 MB max model */

/* ------------------------------------------------------------------ */
/* TLV header helpers (same pattern as wolfBoot sign.c)               */
/* ------------------------------------------------------------------ */

static void header_append_u16(uint8_t *header, uint32_t *idx, uint16_t val)
{
    header[*idx]     = (uint8_t)(val & 0xFF);
    header[*idx + 1] = (uint8_t)((val >> 8) & 0xFF);
    *idx += 2;
}

static void header_append_u32(uint8_t *header, uint32_t *idx, uint32_t val)
{
    header[*idx]     = (uint8_t)(val & 0xFF);
    header[*idx + 1] = (uint8_t)((val >> 8) & 0xFF);
    header[*idx + 2] = (uint8_t)((val >> 16) & 0xFF);
    header[*idx + 3] = (uint8_t)((val >> 24) & 0xFF);
    *idx += 4;
}

static void header_append_tag(uint8_t *header, uint32_t *idx,
                               uint16_t tag, uint16_t len, const void *data)
{
    header_append_u16(header, idx, tag);
    header_append_u16(header, idx, len);
    memcpy(&header[*idx], data, len);
    *idx += len;
}

/* ------------------------------------------------------------------ */
/* Usage                                                              */
/* ------------------------------------------------------------------ */

static void usage(const char *pname)
{
    printf("wolfModel signing tool\n\n");
    printf("Usage: %s --key <ecc256.der> --image <model.bin> --output <model.wmdl>\n"
           "          [--version N] [--type tflite|onnx|raw]\n", pname);
    printf("\nKey file: raw Qx+Qy+d (96 bytes), generated by wolfmodel_keygen\n");
    exit(1);
}

static uint16_t parse_model_type(const char *s)
{
    if (strcmp(s, "tflite") == 0) return WOLFMODEL_TYPE_TFLITE;
    if (strcmp(s, "onnx") == 0)   return WOLFMODEL_TYPE_ONNX;
    if (strcmp(s, "raw") == 0)    return WOLFMODEL_TYPE_RAW;
    return WOLFMODEL_TYPE_UNKNOWN;
}

/* ------------------------------------------------------------------ */
/* Main                                                               */
/* ------------------------------------------------------------------ */

/* Large structs in .bss, not on the stack */
static ecc_key  ecc;
static WC_RNG   rng;
static wc_Sha256 sha;

int main(int argc, char **argv)
{
    /* Command-line options */
    const char *key_file   = NULL;
    const char *image_file = NULL;
    const char *output_file = NULL;
    uint32_t    version    = 1;
    uint16_t    model_type = WOLFMODEL_TYPE_RAW;

    /* Buffers and state */
    uint8_t  header[WOLFMODEL_HEADER_SIZE];
    uint32_t header_idx = 0;
    uint8_t  key_buf[96]; /* Qx+Qy+d */
    uint8_t *image_buf = NULL;
    uint32_t image_sz = 0;
    uint8_t  payload_hash[WC_SHA256_DIGEST_SIZE];
    uint8_t  pubkey_hash[WC_SHA256_DIGEST_SIZE];
    uint8_t  header_hash[WC_SHA256_DIGEST_SIZE];
    uint8_t  signature[WOLFMODEL_SIG_SIZE]; /* r||s = 64 bytes */
    uint32_t sig_offset = 0;
    uint64_t timestamp;
    mp_int   r, s;
    int      ret, i;
    FILE    *f;

    /* Parse arguments */
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--key") == 0 && i + 1 < argc) {
            key_file = argv[++i];
        }
        else if (strcmp(argv[i], "--image") == 0 && i + 1 < argc) {
            image_file = argv[++i];
        }
        else if (strcmp(argv[i], "--output") == 0 && i + 1 < argc) {
            output_file = argv[++i];
        }
        else if (strcmp(argv[i], "--version") == 0 && i + 1 < argc) {
            version = (uint32_t)atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "--type") == 0 && i + 1 < argc) {
            model_type = parse_model_type(argv[++i]);
        }
        else {
            usage(argv[0]);
        }
    }
    if (key_file == NULL || image_file == NULL || output_file == NULL) {
        usage(argv[0]);
    }

    /* ---- Load private key (raw Qx+Qy+d, 96 bytes) ---- */
    f = fopen(key_file, "rb");
    if (f == NULL) {
        fprintf(stderr, "Error: cannot open key file %s: %s\n",
                key_file, strerror(errno));
        return 1;
    }
    if (fread(key_buf, 1, 96, f) != 96) {
        fprintf(stderr, "Error: key file must be 96 bytes (Qx+Qy+d)\n");
        fclose(f);
        return 1;
    }
    fclose(f);

    /* ---- Load image file ---- */
    f = fopen(image_file, "rb");
    if (f == NULL) {
        fprintf(stderr, "Error: cannot open image file %s: %s\n",
                image_file, strerror(errno));
        return 1;
    }
    fseek(f, 0, SEEK_END);
    image_sz = (uint32_t)ftell(f);
    fseek(f, 0, SEEK_SET);
    if (image_sz > MAX_IMAGE_SIZE) {
        fprintf(stderr, "Error: image too large (%u bytes, max %d)\n",
                image_sz, MAX_IMAGE_SIZE);
        fclose(f);
        return 1;
    }
    image_buf = malloc(image_sz);
    if (image_buf == NULL) {
        fprintf(stderr, "Error: malloc failed for image (%u bytes)\n", image_sz);
        fclose(f);
        return 1;
    }
    if (fread(image_buf, 1, image_sz, f) != image_sz) {
        fprintf(stderr, "Error: failed to read image file\n");
        free(image_buf);
        fclose(f);
        return 1;
    }
    fclose(f);

    /* ---- Import ECC key ---- */
    ret = wc_ecc_init(&ecc);
    if (ret != 0) {
        fprintf(stderr, "Error: wc_ecc_init failed (%d)\n", ret);
        free(image_buf);
        return 1;
    }
    ret = wc_ecc_import_unsigned(&ecc,
                                 key_buf,      /* Qx */
                                 key_buf + 32,  /* Qy */
                                 key_buf + 64,  /* d  */
                                 ECC_SECP256R1);
    if (ret != 0) {
        fprintf(stderr, "Error: wc_ecc_import_unsigned failed (%d)\n", ret);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* ---- Compute payload SHA-256 ---- */
    ret = wc_InitSha256(&sha);
    if (ret == 0) ret = wc_Sha256Update(&sha, image_buf, image_sz);
    if (ret == 0) ret = wc_Sha256Final(&sha, payload_hash);
    if (ret != 0) {
        fprintf(stderr, "Error: SHA-256 of payload failed (%d)\n", ret);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* ---- Compute pubkey hint: SHA-256(Qx || Qy) ---- */
    ret = wc_InitSha256(&sha);
    if (ret == 0) ret = wc_Sha256Update(&sha, key_buf, 64); /* Qx+Qy */
    if (ret == 0) ret = wc_Sha256Final(&sha, pubkey_hash);
    if (ret != 0) {
        fprintf(stderr, "Error: SHA-256 of pubkey failed (%d)\n", ret);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* ---- Build header with zeroed signature (zero-and-fill) ---- */
    memset(header, 0xFF, WOLFMODEL_HEADER_SIZE);
    header_idx = 0;

    /* Magic + payload size */
    header_append_u32(header, &header_idx, WOLFMODEL_MAGIC);
    header_append_u32(header, &header_idx, image_sz);

    /* TLV: Version */
    header_append_tag(header, &header_idx, WOLFMODEL_TAG_VERSION, 4,
                      &(uint8_t[4]){
                          (uint8_t)(version & 0xFF),
                          (uint8_t)((version >> 8) & 0xFF),
                          (uint8_t)((version >> 16) & 0xFF),
                          (uint8_t)((version >> 24) & 0xFF)
                      });

    /* TLV: Timestamp */
    timestamp = (uint64_t)time(NULL);
    {
        uint8_t ts_buf[8];
        int j;
        for (j = 0; j < 8; j++)
            ts_buf[j] = (uint8_t)((timestamp >> (j * 8)) & 0xFF);
        header_append_tag(header, &header_idx, WOLFMODEL_TAG_TIMESTAMP, 8,
                          ts_buf);
    }

    /* TLV: SHA-256 of payload */
    header_append_tag(header, &header_idx, WOLFMODEL_TAG_SHA256,
                      WC_SHA256_DIGEST_SIZE, payload_hash);

    /* TLV: Public key hint */
    header_append_tag(header, &header_idx, WOLFMODEL_TAG_PUBKEY_HINT,
                      WC_SHA256_DIGEST_SIZE, pubkey_hash);

    /* TLV: Model type */
    header_append_tag(header, &header_idx, WOLFMODEL_TAG_MODEL_TYPE, 2,
                      &(uint8_t[2]){
                          (uint8_t)(model_type & 0xFF),
                          (uint8_t)((model_type >> 8) & 0xFF)
                      });

    /* TLV: Signature — record sig_offset, fill value with zeros */
    sig_offset = header_idx;
    memset(signature, 0, WOLFMODEL_SIG_SIZE);
    header_append_tag(header, &header_idx, WOLFMODEL_TAG_SIGNATURE,
                      WOLFMODEL_SIG_SIZE, signature);

    /* TLV: End marker */
    header_append_u16(header, &header_idx, WOLFMODEL_TAG_END);

    /* Bounds check */
    if (header_idx > WOLFMODEL_HEADER_SIZE) {
        fprintf(stderr, "Error: TLV content (%u bytes) exceeds header size (%d)\n",
                header_idx, WOLFMODEL_HEADER_SIZE);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* Remaining bytes are already 0xFF from memset above */

    /* ---- Hash the header (with zeroed sig value) ---- */
    ret = wc_InitSha256(&sha);
    if (ret == 0) ret = wc_Sha256Update(&sha, header, WOLFMODEL_HEADER_SIZE);
    if (ret == 0) ret = wc_Sha256Final(&sha, header_hash);
    if (ret != 0) {
        fprintf(stderr, "Error: SHA-256 of header failed (%d)\n", ret);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* ---- Sign the header hash: raw r||s ---- */
    ret = wc_InitRng(&rng);
    if (ret != 0) {
        fprintf(stderr, "Error: wc_InitRng failed (%d)\n", ret);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    mp_init(&r);
    mp_init(&s);
    ret = wc_ecc_sign_hash_ex(header_hash, WC_SHA256_DIGEST_SIZE,
                               &rng, &ecc, &r, &s);
    if (ret != 0) {
        fprintf(stderr, "Error: wc_ecc_sign_hash_ex failed (%d)\n", ret);
        mp_clear(&r);
        mp_clear(&s);
        wc_FreeRng(&rng);
        wc_ecc_free(&ecc);
        free(image_buf);
        return 1;
    }

    /* Export r and s to fixed-size 32-byte buffers */
    memset(signature, 0, WOLFMODEL_SIG_SIZE);
    {
        int rSz = mp_unsigned_bin_size(&r);
        int sSz = mp_unsigned_bin_size(&s);
        /* Right-justify in 32-byte field (zero-pad on left) */
        mp_to_unsigned_bin(&r, &signature[ECC256_KEY_SIZE - rSz]);
        mp_to_unsigned_bin(&s, &signature[WOLFMODEL_SIG_SIZE - sSz]);
    }
    mp_clear(&r);
    mp_clear(&s);
    wc_FreeRng(&rng);
    wc_ecc_free(&ecc);

    /* ---- Drop real signature into header ---- */
    /* sig_offset points to the tag type field; value starts at +4 */
    memcpy(&header[sig_offset + 4], signature, WOLFMODEL_SIG_SIZE);

    /* ---- Write output: header + payload ---- */
    f = fopen(output_file, "wb");
    if (f == NULL) {
        fprintf(stderr, "Error: cannot open output file %s: %s\n",
                output_file, strerror(errno));
        free(image_buf);
        return 1;
    }
    fwrite(header, 1, WOLFMODEL_HEADER_SIZE, f);
    fwrite(image_buf, 1, image_sz, f);
    fclose(f);
    free(image_buf);

    printf("Signed: %s\n", output_file);
    printf("  Payload:   %u bytes\n", image_sz);
    printf("  Version:   %u\n", version);
    printf("  Type:      0x%04X\n", model_type);
    printf("  Sig r||s:  %d bytes at offset %u\n",
           WOLFMODEL_SIG_SIZE, sig_offset);
    printf("  Header:    %d bytes\n", WOLFMODEL_HEADER_SIZE);
    printf("  Total:     %u bytes\n",
           (uint32_t)WOLFMODEL_HEADER_SIZE + image_sz);
    return 0;
}
