/* main.c
 *
 * Copyright (C) 2006-2025 wolfSSL Inc.
 *
 * This file is part of wolfModel.
 *
 * wolfModel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfModel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

#ifndef WOLFSSL_USER_SETTINGS
    #include <wolfssl/options.h>
#endif
#include <wolfssl/wolfcrypt/settings.h>

#include <wolfmodel/wolfmodel.h>

/* Static global — never on the stack (ecc_key is ~400-600 bytes) */
static WOLFMODEL_CTX ctx;

/* Small buffer for the public key (64 bytes: Qx + Qy) */
static uint8_t pubkey_buf[64];

static const char *err_str(int code)
{
    switch (code) {
        case WOLFMODEL_SUCCESS:      return "SUCCESS";
        case WOLFMODEL_BAD_ARG:      return "BAD_ARG";
        case WOLFMODEL_BAD_MAGIC:    return "BAD_MAGIC";
        case WOLFMODEL_BAD_HEADER:   return "BAD_HEADER";
        case WOLFMODEL_BAD_HASH:     return "BAD_HASH (payload tampered)";
        case WOLFMODEL_BAD_SIG:      return "BAD_SIG (signature invalid)";
        case WOLFMODEL_KEY_ERROR:    return "KEY_ERROR (wrong key or hint mismatch)";
        case WOLFMODEL_BAD_VERSION:  return "BAD_VERSION (anti-rollback)";
        case WOLFMODEL_VERIFY_ERROR: return "VERIFY_ERROR (crypto failure)";
        case WOLFMODEL_BAD_RAM_REQ:  return "BAD_RAM_REQ (model too large)";
        default:                     return "UNKNOWN";
    }
}

int main(int argc, char **argv)
{
    const char *wmdl_path;
    const char *key_path;
    int fd;
    struct stat st;
    uint8_t *map;
    FILE *fkey;
    size_t key_sz;
    int ret;
    uint32_t payload_sz;
    const uint8_t *payload;
    uint16_t url_sz;
    const uint8_t *url;

    if (argc != 3) {
        printf("wolfModel verify example\n\n");
        printf("Usage: %s <model.wmdl> <pubkey.der>\n", argv[0]);
        printf("\nKey format: raw Qx+Qy (64 bytes), generated by wolfmodel_keygen\n");
        return 1;
    }

    wmdl_path = argv[1];
    key_path  = argv[2];

    /* 1. mmap the .wmdl file (avoids copying multi-MB models into RAM) */
    fd = open(wmdl_path, O_RDONLY);
    if (fd < 0) {
        perror(wmdl_path);
        return 1;
    }
    if (fstat(fd, &st) < 0) {
        perror("fstat");
        close(fd);
        return 1;
    }
    map = mmap(NULL, (size_t)st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map == MAP_FAILED) {
        perror("mmap");
        close(fd);
        return 1;
    }
    close(fd);

    /* 2. Read pubkey.der (raw Qx+Qy, 64 bytes) */
    fkey = fopen(key_path, "rb");
    if (fkey == NULL) {
        perror(key_path);
        munmap(map, (size_t)st.st_size);
        return 1;
    }
    key_sz = fread(pubkey_buf, 1, sizeof(pubkey_buf), fkey);
    fclose(fkey);
    if (key_sz != 64) {
        fprintf(stderr, "Error: pubkey.der must be 64 bytes (Qx+Qy), got %zu\n",
                key_sz);
        munmap(map, (size_t)st.st_size);
        return 1;
    }

    /* 3. Init */
    ret = wolfModel_Init(&ctx);
    if (ret != WOLFMODEL_SUCCESS) {
        fprintf(stderr, "wolfModel_Init failed: %s (%d)\n", err_str(ret), ret);
        munmap(map, (size_t)st.st_size);
        return 1;
    }

    /* 4. Set public key */
    ret = wolfModel_SetPubKey(&ctx, pubkey_buf, 64);
    if (ret != WOLFMODEL_SUCCESS) {
        fprintf(stderr, "wolfModel_SetPubKey failed: %s (%d)\n", err_str(ret), ret);
        wolfModel_Free(&ctx);
        munmap(map, (size_t)st.st_size);
        return 1;
    }

    /* 5. Verify */
    ret = wolfModel_Verify(&ctx, map, (uint32_t)st.st_size);
    if (ret != WOLFMODEL_SUCCESS) {
        fprintf(stderr, "Verification FAILED: %s (%d)\n", err_str(ret), ret);
        wolfModel_Free(&ctx);
        munmap(map, (size_t)st.st_size);
        return 1;
    }

    /* 6. Get verified payload */
    payload = wolfModel_GetPayload(&ctx, &payload_sz);

    printf("Model verified OK.\n");
    printf("  Version: %u\n", wolfModel_GetVersion(&ctx));
    printf("  Payload: %u bytes\n", payload_sz);

    /* 7. Print AIBOM URL if present */
    url = wolfModel_GetAIBOMUrl(&ctx, &url_sz);
    if (url != NULL && url_sz > 0) {
        printf("  AIBOM:   %.*s\n", url_sz, url);
    }

    (void)payload; /* caller would pass to inference engine */

    /* 8. Cleanup */
    wolfModel_Free(&ctx);
    munmap(map, (size_t)st.st_size);

    return 0;
}
